version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started...
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - '**/*'
