version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo apt-get update -y
      - sudo apt-get install -y nodejs npm
  build:
    commands:
      - echo "Building the application..."
      - npm install
  post_build:
    commands:
      - echo "Build completed!"
artifacts:
  files:
    - '**/*'
